version: "3.9"

networks:
  django_network:

volumes:
  data_volume:
  code_volume:

services:
  db:
    image: postgres
    volumes:
      - data_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - django_network
  web:
    build: .
    volumes:
      - code_volume:/workspaces/python-django-example-app-in-devcontainer/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - django_network
